/**
 * Shape contract for a saved Job item throughout the application pipeline.
 * Updated for Domain-Specific Syncing and Local Vector RAG.
 */
export interface Job {
  /** The clean document title or job position text extracted from the webpage. */
  title: string;
  /** The exact window location href URL serving as the origin of the job post. */
  url: string;
  /** The root domain name used for Google Drive folder organization (e.g., "openai"). */
  company: string;
  /** The pristine plain text of the job description used by Gemini Nano for RAG. */
  cleanText: string;
  /** The vector representation generated by Transformers.js for semantic similarity search. */
  embedding: number[];
  /** Unix timestamp sequence representing precisely when the job entry was saved. */
  savedAt: number;
}
